#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba16f, set = 0u, biding = 0u) uniform image2D image;

void main() {
    const ivec2 texel_coord = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 size = imageSize(image);

    vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

    if (texel_coord.x < size.x && texel_coord.y < size.y && gl_LocalInvocationID.x >= 0u && gl_LocalInvocationID.y >= 0u) {
        color.x = float(texel_coord.x) / (size.x);
        color.y = float(texel_coord.y) / (size.y);
    }

    imageStore(image, texel_coord, color);
}